const mongoose=require("mongoose");
const express=require("express")

mongoose.connect(process.env.MONGO_CONNECTER)
.then(()=>{console.log("connection established with mongodb on collection order")})
.catch((e)=>{console.error(e.message)})
const orderSchema = new mongoose.Schema({
    username:{
        type:String,
        required:true
    },
    name:{
        type:String,
        required:true
    },
    date:{
        type:Date,
        required:true
    },
    orderDate:{
        type:String,
        required:true
    },
    orderTime:{
        type:String,
        required:true
    },
    price:{
        type:Number,
        required:true
    },
    totalPrice:{
        type:Number,
        required:false
    },
    orderId:{
        type:String,
        required:true
    },
    status:{
        type:Array,
        required:true
    },
    payment:{
        type:String,
        required:true
    },
    coupon:{
        type:String,
        required:false
    },
    adminCancel:{
        type:Number,
        required:true
    },
    product:{
        type:String,
        required:true
    },
    quantity:{
        type:Number,
        required:true
    },
    image:{
        type:Array,
        required:true
        },
    address:{
        houseName:{
            type:String,
            required:true
        },
        city:{
            type:String,
            required:true
        },
        state:{
            type:String,
            required:true
        },
        pincode:{
            type:Number,
            required:true
        },
        country:{
            type:String,
            required:true
        },
        phone:{
            type:Number,
            required:true
        }
    },
    reason:{
        type:String,
        required:false
    }
})
module.exports=mongoose.model("orders",orderSchema);